artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  data_path: data/train.csv
  train_data_path: artifacts/data_ingestion/train.csv
  test_data_path: artifacts/data_ingestion/test.csv


data_transformation:
  root_dir: artifacts/data_transformation
  preprocessed_obj_file_path: artifacts/data_transformation/preprocessor.pkl


model_trainer:
  root_dir: artifacts/model_trainer
  model_file_path: artifacts/model_trainer/model.pkl
