artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  data_train_path: data/train.csv
  data_test_path: data/test.csv
  train_data_path: artifacts/data_ingestion/train.csv
  test_data_path: artifacts/data_ingestion/test.csv


data_validation:
  train_data_path: artifacts/data_ingestion/train.csv
  test_data_path: artifacts/data_ingestion/test.csv


data_transformation:
  root_dir: artifacts/data_transformation
  preprocessed_obj_file_path: artifacts/data_transformation/preprocessor.pkl
  train_arr_path: artifacts/data_transformation/train.npz
  test_arr_path: artifacts/data_transformation/test.npz
  train_data_path: artifacts/data_ingestion/train.csv
  test_data_path: artifacts/data_ingestion/test.csv


model_trainer:
  root_dir: artifacts/model_trainer
  model_file_path: artifacts/model_trainer/model.pkl
  train_arr_path: artifacts/data_transformation/train.npz
  test_arr_path: artifacts/data_transformation/test.npz
